# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 06:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20170210_0602'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0002_contact_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together=set([('user', 'person')]),
        ),
    ]
