# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 19:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0004_auto_20170210_0602'),
        ('contacts', '0003_auto_20170210_0602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='data.Person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='contact',
            name='person',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
        migrations.RenameField(
            model_name='interaction',
            old_name='interaction_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='contact',
        ),
        migrations.AddField(
            model_name='interaction',
            name='person',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='data.Person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interaction',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together=set([('user', 'person')]),
        ),
    ]
