# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 02:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20170210_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interaction',
            old_name='title',
            new_name='label',
        ),
    ]
