# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_interaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
