# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170214_1731'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useraccount',
            unique_together=set([('user', 'account')]),
        ),
    ]
