# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170214_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='data.Company'),
        ),
    ]
