# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170214_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
