# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170221_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='data.Person'),
        ),
    ]
