# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20170221_2135'),
        ('users', '0006_auto_20170221_0637'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPortfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_portfolio', to='users.Account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_portfolio', to='data.Company')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='accountportfolio',
            unique_together=set([('account', 'company')]),
        ),
    ]
