# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20170324_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.Account'),
            preserve_default=False,
        ),
    ]
