# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_data_20170329_1832'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useraccount',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='account',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='user',
        ),
        migrations.AlterField(
            model_name='account',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_company', to='data.Company'),
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
