# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 07:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment', to='data.Company'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment', to='data.Person'),
        ),
    ]
