# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20170209_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
