# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_employment_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='current',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
