# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20170210_0602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=25)),
                ('date', models.DateField(blank=True, null=True)),
                ('pre_money', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('raised', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('post_money', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='data.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InvestorInvestment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('lead', models.NullBooleanField()),
                ('ownership', models.FloatField(blank=True, null=True)),
                ('invested', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('shares', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_investments', to='data.Investment')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investor_investments', to='data.Investor')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='investor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Investor'),
        ),
        migrations.AddField(
            model_name='person',
            name='investor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Investor'),
        ),
        migrations.AlterUniqueTogether(
            name='investorinvestment',
            unique_together=set([('investment', 'investor', 'date')]),
        ),
        migrations.AlterUniqueTogether(
            name='investment',
            unique_together=set([('company', 'series')]),
        ),
    ]
