# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_boardmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmember',
            name='current',
            field=models.NullBooleanField(default=True),
        ),
    ]
