# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20170215_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='conversion_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='preference_dollars',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='preference_multiple',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='seniority',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='share_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True),
        ),
    ]
