# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20170217_0900'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='investorinvestment',
            unique_together=set([('investment', 'investor')]),
        ),
    ]
