# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20170221_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='sector',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='segment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
