# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20170221_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='crunchbase_id',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='company',
            name='crunchbase_permalink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='type',
            field=models.TextField(choices=[(b'PERSON', b'Person'), (b'COMPANY', b'Company')], default=b'COMPANY'),
        ),
    ]
