# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 23:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20170221_2318'),
        ('data', '0014_company_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('stage', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(default=b'users.DEFAULT_ACCOUNT_ID', on_delete=django.db.models.deletion.CASCADE, to='users.Account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='data.Company')),
            ],
        ),
        migrations.AlterField(
            model_name='investment',
            name='series',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='investment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Investment'),
        ),
        migrations.AddField(
            model_name='deal',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_deals', to='data.Person'),
        ),
        migrations.AddField(
            model_name='deal',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrer_deals', to='data.Person'),
        ),
    ]
