# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20170324_0221'),
        ('data', '0016_auto_20170323_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='investor',
        ),
        migrations.RemoveField(
            model_name='person',
            name='investor',
        ),
        migrations.AddField(
            model_name='boardmember',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='board_members', to='users.Account'),
        ),
        migrations.AddField(
            model_name='company',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='users.Account'),
        ),
        migrations.AddField(
            model_name='companytag',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_tags', to='users.Account'),
        ),
        migrations.AddField(
            model_name='employment',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employments', to='users.Account'),
        ),
        migrations.AddField(
            model_name='investment',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='users.Account'),
        ),
        migrations.AddField(
            model_name='investor',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='investors', to='users.Account'),
        ),
        migrations.AddField(
            model_name='investor',
            name='company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Company'),
        ),
        migrations.AddField(
            model_name='investor',
            name='person',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Person'),
        ),
        migrations.AddField(
            model_name='investorinvestment',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='investor_investments', to='users.Account'),
        ),
        migrations.AddField(
            model_name='metric',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='users.Account'),
        ),
        migrations.AddField(
            model_name='metricvalue',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='metric_values', to='users.Account'),
        ),
        migrations.AddField(
            model_name='person',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='people', to='users.Account'),
        ),
        migrations.AddField(
            model_name='persontag',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='person_tags', to='users.Account'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.TextField(default='Unknown'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deal',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='users.Account'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='name',
            field=models.TextField(default='Unknown'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='investment',
            name='series',
            field=models.TextField(default='Series Unknown'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='companytag',
            unique_together=set([('account', 'company', 'tag')]),
        ),
        migrations.AlterUniqueTogether(
            name='investment',
            unique_together=set([('account', 'company', 'series')]),
        ),
        migrations.AlterUniqueTogether(
            name='investor',
            unique_together=set([('account', 'person'), ('account', 'company')]),
        ),
        migrations.AlterUniqueTogether(
            name='investorinvestment',
            unique_together=set([('account', 'investment', 'investor')]),
        ),
        migrations.AlterUniqueTogether(
            name='metric',
            unique_together=set([('account', 'company', 'name', 'interval', 'estimated')]),
        ),
        migrations.AlterUniqueTogether(
            name='metricvalue',
            unique_together=set([('account', 'metric', 'date')]),
        ),
        migrations.AlterUniqueTogether(
            name='persontag',
            unique_together=set([('account', 'person', 'tag')]),
        ),
    ]
