# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-13 07:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20170513_0710'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0017_auto_20170324_0225'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='custom_data', to='users.Account')),
            ],
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.TextField()),
                ('api_name', models.TextField()),
                ('type', models.TextField(choices=[(b'string', b'string'), (b'money', b'money'), (b'image', b'image'), (b'number', b'number'), (b'text', b'text'), (b'date', b'date'), (b'model', b'model')])),
                ('required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='users.Account')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to=settings.AUTH_USER_MODEL)),
                ('related_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_custom_fields', to='data.CustomField')),
            ],
        ),
        migrations.CreateModel(
            name='CustomRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='custom_records', to='users.Account')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.TextField()),
                ('api_name', models.TextField()),
                ('icon', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='custom_tables', to='users.Account')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_tables', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='deal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customrecord',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_records', to='data.CustomTable'),
        ),
        migrations.AddField(
            model_name='customfield',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='data.CustomTable'),
        ),
        migrations.AddField(
            model_name='customdata',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_data', to='data.CustomField'),
        ),
        migrations.AddField(
            model_name='customdata',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customdata',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_data', to='data.CustomRecord'),
        ),
        migrations.AlterUniqueTogether(
            name='customtable',
            unique_together=set([('account', 'api_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='customfield',
            unique_together=set([('table', 'api_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='customdata',
            unique_together=set([('field', 'record')]),
        ),
    ]
