# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-24 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_data_auto_20170524_2046'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataSource',
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='source',
        ),
        migrations.AlterField(
            model_name='customdata',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_data', to='data.CustomFieldIntegration'),
        ),
        migrations.AlterUniqueTogether(
            name='customfieldintegration',
            unique_together=set([('account', 'field', 'integration')]),
        ),
        migrations.AlterUniqueTogether(
            name='apiintegrationsource',
            unique_together=set([('integration', 'model', 'field')]),
        ),
    ]
