# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-26 00:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_data_auto_20170526_0016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasource',
            old_name='source_display',
            new_name='display',
        ),
        migrations.RenameField(
            model_name='datasource',
            old_name='source_icon',
            new_name='icon',
        ),
        migrations.RenameField(
            model_name='datasource',
            old_name='source',
            new_name='name',
        ),
    ]
